/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ChatChatlistidImport } from './routes/chat/$chatlistid'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChatChatlistidRoute = ChatChatlistidImport.update({
  id: '/chat/$chatlistid',
  path: '/chat/$chatlistid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chat/$chatlistid': {
      id: '/chat/$chatlistid'
      path: '/chat/$chatlistid'
      fullPath: '/chat/$chatlistid'
      preLoaderRoute: typeof ChatChatlistidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/$chatlistid': typeof ChatChatlistidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$chatlistid': typeof ChatChatlistidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/chat/$chatlistid': typeof ChatChatlistidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat/$chatlistid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$chatlistid'
  id: '__root__' | '/' | '/chat/$chatlistid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatChatlistidRoute: typeof ChatChatlistidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatChatlistidRoute: ChatChatlistidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat/$chatlistid"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chat/$chatlistid": {
      "filePath": "chat/$chatlistid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
